#!/bin/bash

### ShadowFox updater for Mac/Linux
## author: @overdodactyl
## version: 1.0

## get the full path of this script (readlink for Linux, greadlink for Mac with coreutils installed)
sfp=$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || greadlink -f "${BASH_SOURCE[0]}" 2>/dev/null)

## fallback for Macs without coreutils
if [ -z "$sfp" ]; then sfp=${BASH_SOURCE[0]}; fi

## change directory to the Firefox profile directory
cd "$(dirname "${sfp}")"

## create a pull request using git
git pull


## Add any gulp tasks here. Examples commented out below:
## gulp userContent_amo
## gulp userChrome_basic
